export default {
  login: "Ndukwechima",
  id: 58550127,
  node_id: "MDQ6VXNlcjU4NTUwMTI3",
  avatar_url: "https://avatars.githubusercontent.com/u/58550127?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/Ndukwechima",
  html_url: "https://github.com/Ndukwechima",
  followers_url: "https://api.github.com/users/Ndukwechima/followers",
  following_url:
    "https://api.github.com/users/Ndukwechima/following{/other_user}",
  gists_url: "https://api.github.com/users/Ndukwechima/gists{/gist_id}",
  starred_url:
    "https://api.github.com/users/Ndukwechima/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/Ndukwechima/subscriptions",
  organizations_url: "https://api.github.com/users/Ndukwechima/orgs",
  repos_url: "https://api.github.com/users/Ndukwechima/repos",
  events_url: "https://api.github.com/users/Ndukwechima/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/Ndukwechima/received_events",
  type: "User",
  user_view_type: "public",
  site_admin: false,
  name: "Chima Arubuike Ndukwe",
  company: null,
  blog: "https://chima-aruby-dev-portfolio.vercel.app/",
  location: "Nigeria",
  email: null,
  hireable: null,
  bio: "Frontend Developer | React & Next.js | Typescript  Enthusiast | Building Responsive, Scalable Web Applications.",
  twitter_username: null,
  public_repos: 41,
  public_gists: 0,
  followers: 0,
  following: 0,
  created_at: "2019-12-05T09:11:26Z",
  updated_at: "2025-06-02T12:59:43Z",
};